#!/usr/bin/python3

import subprocess
import os
import sys

try:
    subprocess.run(
        'python3 -m photonai run'
        ' -b photonai/tests/bots/nothing.py'
        ' -b examples/spiral.py'
        ' -o /tmp/simulation.avro'
        ' --force',
        shell=True, check=True,
        stderr=subprocess.PIPE)

except subprocess.CalledProcessError as e:
    sys.stderr.write('==== Subprocess stderr ====\n')
    sys.stderr.write(e.stderr.decode('utf8'))
    sys.stderr.write('===========================\n')
    raise


assert os.path.exists('/tmp/simulation.avro')
os.remove('/tmp/simulation.avro')
